export const demoIncident = {
  id: "demo-31337",
  chainId: 31_337,
  chainName: "Local Anvil",
  source: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
  destination: "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65",
  attackerSink: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  contracts: {
    token: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    nft: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    airdrop: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    attackerSimulation: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
  },
  evidence: [
    {
      id: "asset:srt",
      type: "ERC-20",
      name: "RescueToken",
      amount: "100 SRT",
      detail: "18 decimals",
      status: "DETECTED",
    },
    {
      id: "asset:nft:1",
      type: "ERC-721",
      name: "SAFEEXIT Demo NFT",
      amount: "Token #1",
      detail: "Owned by source",
      status: "DETECTED",
    },
    {
      id: "claim:srt",
      type: "CLAIM",
      name: "DemoAirdrop reward",
      amount: "50 SRT",
      detail: "claimable(source)",
      status: "DETECTED",
    },
  ],
  approvals: [
    {
      id: "approval:demo-attacker",
      type: "ERC-20 allowance",
      amount: "25 SRT",
      spender: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      status: "DETECTED",
    },
  ],
  actions: [
    {
      id: "action:claim",
      number: "01",
      title: "Claim configured reward",
      signature: "claim()",
      target: "airdrop",
      effect: "+50 SRT to source",
      risk: "HIGH",
      dependencies: "None",
    },
    {
      id: "action:token",
      number: "02",
      title: "Transfer RescueToken",
      signature: "transfer(destination, 150 SRT)",
      target: "token",
      effect: "150 SRT to destination",
      risk: "HIGH",
      dependencies: "Action 01",
    },
    {
      id: "action:nft",
      number: "03",
      title: "Transfer Demo NFT #1",
      signature: "safeTransferFrom(source, destination, 1)",
      target: "nft",
      effect: "NFT #1 to destination",
      risk: "HIGH",
      dependencies: "None",
    },
    {
      id: "action:revoke",
      number: "04",
      title: "Revoke demo allowance",
      signature: "approve(attackerSimulation, 0)",
      target: "token",
      effect: "Allowance set to zero",
      risk: "HIGH",
      dependencies: "Actions 02 and 03",
    },
  ],
  verification: [
    { label: "Claim and rescue flow", result: "PASS", source: "Foundry test" },
    { label: "Fixed attacker target", result: "PASS", source: "Foundry test" },
    { label: "Post-revocation sweep", result: "REVERTED", source: "Expected result" },
    { label: "Gas estimates", result: "NOT CAPTURED", source: "Dashboard fixture" },
  ],
} as const;

export type DemoIncident = typeof demoIncident;
